version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
#    env_file:
#      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docker-db
    ports:
      - '5432:5432'
    networks:
      - backend
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
#    env_file:
#      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: lucas@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - '80:80'
    networks:
      - backend
  docker-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    container_name: docker-api
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:postgresql://postgres:5432/docker-db",
        "spring.datasource.driver-class-name" : "org.postgresql.Driver",
        "spring.datasource.username" : "postgres",
        "spring.datasource.password" : "postgres",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.database-platform" : "org.hibernate.dialect.PostgreSQLDialect",
        "server.port" : "8081"
      }'
#    env_file:
#      - .env
    depends_on:
      - postgres
      - pgadmin
    networks:
      - backend
networks:
  backend:
    driver: bridge


