server:
  port: 8081

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/docker-db}
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect